FROM maven:3.9.11-eclipse-temurin-17-alpine AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17.0.16_8-jre-alpine-3.22
WORKDIR /app
COPY --from=build /app/target/WalletProcessor-0.0.1-SNAPSHOT.jar .
CMD ["java","jar","WalletProcessor-0.0.1-SNAPSHOT.jar"]
