spring.application.name=Controle-Financeiro

spring.datasource.url=jdbc:postgresql://localhost:5432/CarteiraFinanceira
spring.datasource.username=postgres
spring.datasource.password=banco123
spring.jpa.hibernate.ddl-auto=update


wallet-storage.url=http://localhost:8083
stockfetcher.url=http://localhost:8081