spring.application.name=StockFetcher

server.port=8081

# Configurações do Cache
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=30m,recordStats
spring.cache.cache-names=stockCache
spring.cache.type=caffeine

app.cache.stale-threshold=15
app.cache.stale-threshold-minutes=15

# Paralelismo e Throttling
app.api.max-parallel-requests=4
app.api.request-delay-ms=350
app.api.batch-size=20
app.api.batch-delay-ms=2000

# Configurações de Retry
app.retry.max-attempts=3
app.retry.initial-delay=1000
app.retry.multiplier=2

# URL da API Yahoo Finance
app.yahoo-api.url=https://query1.finance.yahoo.com/v8/finance/chart/{symbol}.SA?interval=1d&range=1mo

# Habilita estatísticas do cache (para o endpoint /cache-info)
management.endpoint.cachestats.enabled=true
management.endpoints.web.exposure.include=cachestats,health,metrics,info
management.endpoint.health.show-details=always

