spring.application.name=WalletStorage


spring.datasource.url=jdbc:postgresql://localhost:5432/CarteiraFinanceira
spring.datasource.username=postgres
spring.datasource.password=banco123
spring.jpa.hibernate.ddl-auto=update

# configuração para o data.sql rodar depois do JPA
spring.jpa.defer-datasource-initialization=true

# conf para rodar o data.sql
spring.sql.init.mode=always

server.port =8083

