INSERT INTO asset_auto_complete (id, name, symbol) VALUES
       (1,'Petrobras PN','PETR4'),
       (2,'Petrobras ON','PETR3'),
       (3,'Vale ON','VALE3'),
       (4,'Itaú Unibanco PN','ITUB4'),
       (5,'Banco do Brasil ON','BBAS3'),
       (6,'Bradesco PN','BBDC4'),
       (7,'Bradesco ON','BBDC3'),
       (8,'Ambev ON','ABEV3'),
       (9,'WEG ON','WEGE3'),
       (10,'Magazine Luiza ON','MGLU3'),
       (11,'B3 ON','B3SA3'),
       (12,'Natura ON','NTCO3'),
       (13,'Suzano ON','SUZB3'),
       (14,'Gerdau PN','GGBR4'),
       (15,'JBS ON','JBSS3'),
       (16,'Localiza ON','RENT3'),
       (17,'Raia Drogasil ON','RADL3'),
       (18,'CPFL Energia ON','CPFE3'),
       (19,'Eletrobras ON','ELET3'),
       (20,'Eletrobras PN','ELET6'),
       (21,'Apple','AAPL'),
       (22,'Microsoft','MSFT'),
       (23,'Amazon','AMZN'),
       (24,'Google (Alphabet A)','GOOGL'),
       (25,'Google (Alphabet C)','GOOG'),
       (26,'Meta (Facebook)','META'),
       (27,'Tesla','TSLA'),
       (28,'NVIDIA','NVDA'),
       (29,'Netflix','NFLX'),
       (30,'Intel','INTC'),
       (31,'AMD','AMD'),
       (32,'Uber','UBER'),
       (33,'Airbnb','ABNB'),
       (34,'Spotify','SPOT'),
       (35,'Salesforce','CRM'),
       (36,'Adobe','ADBE'),
       (37,'PayPal','PYPL'),
       (38,'Oracle','ORCL'),
       (39,'IBM','IBM'),
       (40,'Cisco','CSCO'),
       (41,'Coca-Cola','KO'),
       (42,'PepsiCo','PEP'),
       (43,'McDonald''s','MCD'),
       (44,'Walmart','WMT'),
       (45,'Nike','NKE'),
       (46,'Disney','DIS'),
       (47,'Starbucks','SBUX'),
       (48,'Visa','V'),
       (49,'Mastercard','MA'),
       (50,'Goldman Sachs','GS'),
       (51,'Johnson & Johnson','JNJ'),
       (52,'Pfizer','PFE'),
       (53,'Moderna','MRNA'),
       (54,'AbbVie','ABBV'),
       (55,'Merck','MRK'),
       (56,'Exxon Mobil','XOM'),
       (57,'Chevron','CVX'),
       (58,'Shell','SHEL'),
       (59,'BP','BP'),
       (60,'Alibaba','BABA'),
       (61,'Tencent','TCEHY'),
       (62,'Baidu','BIDU'),
       (63,'JD.com','JD'),
       (64,'Shopify','SHOP'),
       (65,'Square (Block)','SQ'),
       (66,'Zoom','ZM'),
       (67,'Snowflake','SNOW'),
       (68,'Palantir','PLTR'),
       (69,'Banco Inter','INBR32'),
       (70,'BTG Pactual','BPAC11'),
       (71,'XP Inc','XP'),
       (72,'PagSeguro','PAGS'),
       (73,'Stone','STNE'),
       (74,'PetroRio','PRIO3'),
       (75,'3R Petroleum','RRRP3'),
       (76,'BRF','BRFS3'),
       (77,'Marfrig','MRFG3'),
       (78,'Embraer','EMBR3'),
       (79,'Azul','AZUL4'),
       (80,'Gol','GOLL4'),
       (81,'Hapvida','HAPV3'),
       (82,'Qualicorp','QUAL3'),
       (83,'Fleury','FLRY3'),
       (84,'CVC','CVCB3'),
       (85,'Via','VIIA3'),
       (86,'Americanas','AMER3'),
       (87,'Alpargatas','ALPA4'),
       (88,'Ecorodovias','ECOR3'),
       (89,'CSHG Logística','HGLG11'),
       (90,'XP Malls','XPML11'),
       (91,'Kinea Renda Imobiliária','KNRI11'),
       (92,'BTG Pactual Logística','BTLG11'),
       (93,'CSHG Renda Urbana','HGRU11'),
       (94,'HSI Logística','HSLG11'),
       (95,'Vinci Shopping Centers','VISC11'),
       (96,'Vinci Offices','VINO11'),
       (97,'CXP Logística','CXTL11'),
       (98,'Kinea Securities','KNSC11'),
       (99,'Kinea Índices de Preços','KNIP11'),
       (100,'Kinea Rendimentos Imobiliários','KNCR11'),
       (101,'Maxi Renda','MXRF11'),
       (102,'Mauá Capital Recebíveis','MCCI11'),
       (103,'Iridium Recebíveis','IRDM11'),
       (104,'Valora RE','VGIR11'),
       (105,'RBR High Grade','RBRR11'),
       (106,'RBR Alpha','RBRF11'),
       (107,'XP Crédito Imobiliário','XPCI11'),
       (108,'XP Corporate Macaé','XPCM11'),
       (109,'XP Properties','XPPR11'),
       (110,'XP Industrial','XPIN11'),
       (111,'BTG Pactual Corporate Office Fund','BRCR11'),
       (112,'CSHG Prime Offices','HGPO11'),
       (113,'FII Torre Norte','TRNT11'),
       (114,'Tellus Properties','TEPP11'),
       (115,'FII Rio Bravo Renda Corporativa','RCRB11'),
       (116,'FII Shopping Pátio Higienópolis','SHPH11'),
       (117,'FII Shopping Parque Dom Pedro','PQDP11'),
       (118,'Hospital da Criança','HCRI11'),
       (119,'Hospital Nossa Senhora de Lourdes','NSLU11'),
       (120,'FII Inter DTVM','ITIT11'),
       (121,'FII VBI Prime Properties','PVBI11'),
       (122,'FII Hedge Top FOFII','HFOF11'),
       (123,'FII Hedge Brasil Shopping','HGBS11'),
       (124,'FII BTG Pactual Fundo de Fundos','BCFF11'),
       (125,'FII Capitânia Securities','CPTS11'),
       (126,'FII Vinci Logística','VILG11'),
       (127,'FII Vinci Renda Urbana','VIFI11'),
       (128,'FII JS Real Estate','JSRE11'),
       (129,'FII Pátria Logística','PATL11'),
       (130,'FII Guardian Logística','GALG11'),
       (131,'FII TRX Real Estate','TRXF11'),
       (132,'FII Suno Recebíveis','SNCI11'),
       (133,'FII Suno Logística','SNLG11'),
       (134,'FII Alianza Trust Renda Imobiliária','ALZR11'),
       (135,'FII Kinea Oportunidades','KOPI11'),
       (136,'FII Mogno CRI High Yield','MGCR11'),
       (137,'FII Rio Bravo Crédito Imobiliário','RBVA11'),
       (138,'FII Rio Bravo Logística','RBLG11'),
       (139,'FII Ourinvest Logística','OULG11'),
       (140,'FII BB Progressivo II','BBPO11'),
       (141,'FII Santander Renda de Aluguéis','SARE11'),
       (142,'FII Mérito Desenvolvimento','MFII11')
    ON CONFLICT (id) DO NOTHING;